spring.application.name=Biblioteca

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Projeto02
spring.datasource.username=postgres
spring.datasource.password=141209
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Security Configuration (Permit all for simplicity in this demo, but can be locked down)
spring.security.user.name=admin
spring.security.user.password=admin
